version: "3.9"

services:
    moviecatalogapplication:
        image:  moviecatalogapplication:latest
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            ConnectionStrings__DefaultConnection: "Data Source=/app/storage/Test.db"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_HTTP_PORTS: "80"
        volumes:
            - mca_data:/app/storage
    db:
        image: mariadb:latest
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: rootuser
            MYSQL_DATABASE: ratings
            MYSQL_PASSWORD: test123
            MYSQL_ROOT_PASSWORD: test123
            
volumes:
    db_data:
    mca_data: