version: "3.9"

services:
    moviegateway:
        image:  movieapigateway:latest
        ports:
            - "8082:8082"
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_HTTP_PORTS: "8082"
   
    moviecatalogapplication:
        image:  moviecatalogapplication:latest
        ports:
            - "8080:80"
        environment:
            ConnectionStrings__DefaultConnection: "Data Source=/app/storage/Catalog.db"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_HTTP_PORTS: "80"
            APIS__ReviewAPI: "http://moviereviewapplication:8080/api/v1/MovieRatings"
        volumes:
            - mca_data:/app/storage
    moviereviewapplication:
        image:  movieratingapplication:latest
        depends_on:
            - reviewdb
        ports:
            - "8081:8080"
        environment:
            ConnectionStrings__DefaultConnection: "Host=reviewdb;Port=3306;Database=ratings;UID=rootuser;PWD=test123"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_HTTP_PORTS: "8080"   
        volumes:
            - mca_data:/app/storage
    moviestreamapplication:
        image:  moviestreamingapplication:latest
        depends_on:
            - reviewdb
        ports:
            - "8083:8083"
        environment:
            ConnectionStrings__DefaultConnection: "Data Source=/app/storage/Stream.db"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_HTTP_PORTS: "8083"   
        volumes:
            - msa_data:/app/storage
    reviewdb:
        image: mariadb:latest
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: rootuser
            MYSQL_DATABASE: ratings
            MYSQL_PASSWORD: test123
            MYSQL_ROOT_PASSWORD: test123
            
volumes:
    db_data:
    mca_data:
    msa_data:
