name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/Backend/MovieBackend
          file: ./src/Backend/MovieBackend/Services/MovieCatalog/MovieCatalog.Application/Dockerfile
          push: true
          tags: mkpatrick/moviecatalog
          platforms: linux/amd64,linux/arm64
