name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
      - name: Build docker image
        working-directory: src/Backend/MovieBackend
        run: docker build -t mkpatrick/moviecatalog -f Services/MovieCatalog/MovieCatalog.Application/Dockerfile .
      - name: Push docker image
        run: docker push mkpatrick/moviecatalog
